version: '3.9'
services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: mysql-db
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3308:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3308/mysql-db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpass

  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend